### ISSUE TITLE
Microsoft sample to detect onvif devices. 

### ISSUE THREAD

**Issue by ahasan016** [AM687/WS-Discovery#1]
Hello,
Can i use your Microsoft sample to detecr all the onvif supported devices in my network?

**Comment by georgSquared** [comment]
Hey @ahasan016,

If you are asking from a "licensing" perspective, you are of course free to use any of the code as you see fit. Most of it (if not all) is taken from external sources.

If you need instruction on how to use the samples, I am afraid I can't really help you. This is a very old repo, for an old university course and  has not been maintained since.
